config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :tracks
  resources :shows

  get 'bio', to: 'pages#bio', as: :bio
  # get 'music', to: 'pages#music', as: :music


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match '/contact',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Tsunami Booking Inquiry",
      # :to => "djtsunami7@gmail.com",
      :to => "ryanmansfield86@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/show.rb
class Show < ApplicationRecord
end

app/models/track.rb
class Track < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create, :new]

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :bio]

  def home
  end

  def bio
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @shows = Show.all
  end

  def show          # GET /shows/:id
  end

  def new           # GET /shows/new
  end

  def create        # POST /shows
  end

  def edit          # GET /shows/:id/edit
  end

  def update        # PATCH /shows/:id
  end

  def destroy       # DELETE /shows/:id
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @tracks = Track.all
  end

  def show          # GET /shows/:id
  end

  def new           # GET /shows/new
  end

  def create        # POST /shows
  end

  def edit          # GET /shows/:id/edit
  end

  def update        # PATCH /shows/:id
  end

  def destroy       # DELETE /shows/:id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="contact">
  <%= render 'shared/banner' %>
  <div class="contact-form">
    <div class="container">
      <div align="center">
        <h3>Send me an Email</h3>
        <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
          <%= f.input :name, :required => true %>
          <%= f.input :email, :required => true %>
          <%= f.input :message, :as => :text, :required => true %>
          <div class= "hidden">
            <%= f.input :nickname, :hint => 'Leave this field blank!' %>
          </div>
          <div>
            </br>
            <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tsunami</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%#= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1550520115-e9b95e845e4c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80);">
  <div class="nav-links">
    <%= link_to "Home", root_path, class: "nav-link" %>
    <%= link_to "Bio", bio_path, class: "nav-link" %>
    <%= link_to "Shows", shows_path, class: "nav-link" %>
    <%= link_to "Music", music_path, class: "nav-link" %>
    <%= link_to "Booking", booking_path, class: "nav-link" %>
  </div>
  <div class="container">
    <h1>Tsunami</h1>
  </div>
</div>

app/views/pages/bio.html.erb
<div class="bio">
  <%= render 'shared/banner' %>

  <!-- Content -->
  <div class="container">
    <div class="about">
      <p>With deep roots as a drummer and percussionist, it was only natural that Chicago native Erik Johnson was drawn to the beat of dance music at an early age. As Tsunami, he has graced the turntables at venues in the windy city and across the United States for more than a decade, all while releasing original music and remixes on iconic labels such as Moody Recordings, Toolroom, Trax Records and Phunk Junk, as well as co-finding the infamous Chicago party brand "Afterlife". Tsunami's Toolroom Records collaboration with Mike Vale entitled "Domina" received support from Mark Knight on Toolroom Radio and was a favorite off the Ibiza 2017 compilation. As a DJ, 2019 has been Tsunami's most monumental year yet, locking down coveted performances at festivals such as Spring Awakening, Electric Forest, and North Coast, as well as being selected as the winner of Insomniac's Discovery Project for EDC Orlando 2019, securing him a slot at the fest. His original track "Green Light District" was featured on the legendary Trax Records' 35 Years Of House Music compilation, and was supported internationally by some of dance music's giants. You can currently find him holding down residencies at many of Chicago's top nightclubs, and in the studio mastering his craft.
      </p>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/pages/home.html.erb
<div class="home" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://scontent-msp1-1.xx.fbcdn.net/v/t31.0-8/857066_699225503521062_2937917581656613269_o.jpg?_nc_cat=101&_nc_ohc=i3a21ChY6ywAQke7XQbb8QfZgYqavJh4KmhKg6wAQdUp9y8wjZezUTkBQ&_nc_ht=scontent-msp1-1.xx&oh=a49a2e4b71c17ed14e6aabb294e08c53&oe=5E6D2785);">
  <div class="nav-links">
    <%= link_to "Bio", bio_path, class: "nav-link" %>
    <%= link_to "Shows", shows_path, class: "nav-link" %>
    <%= link_to "Music", tracks_path, class: "nav-link" %>
    <%= link_to "Contact", contact_path, class: "nav-link" %>
  </div>
  <div class="home-container">
    <div class="home-content">
      <h1 class="title">Tsunami</h1>
      <div class="social-links">
        <a href="https://www.facebook.com/DJTsunami/" target="_blank">
          <i class="fab fa-facebook-square"></i>
        </a>
        <a href="https://soundcloud.com/djtsunamichii?fbclid=IwAR1E7fFCVCcJpn2Q-n-L9wPFYu6Bh8dC5ZoO6rnVDBKTjb2HT1B6MXWXk5g" target="_blank">
          <i class="fab fa-soundcloud"></i>
        </a>
        <a href="https://www.instagram.com/djtsunami/" target="_blank">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="https://open.spotify.com/artist/5UqnbnezI2TvaTWKwYhyrP" target="_blank">
          <i class="fab fa-spotify"></i>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1550520115-e9b95e845e4c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80);">
  <div class="nav-links">
    <%= link_to "Home", root_path, class: "nav-link" %>
    <%= link_to "Bio", bio_path, class: "nav-link" %>
    <%= link_to "Shows", shows_path, class: "nav-link" %>
    <%= link_to "Music", tracks_path, class: "nav-link" %>
    <%= link_to "Contact", contact_path, class: "nav-link" %>
  </div>
  <div class="container">
    <h1 class="title">Tsunami</h1>
  </div>
</div>

app/views/shared/_card-track.html.erb
<%@tracks.each do |track| %>
  <div class="card">
    <div class="card-track">
      <% track.image %>
      <img src="<%= track.image %>" />
      <div class="card-track-infos">
        <div>
          <h2><%= track.name %></h2>
        </div>
        <h2 class="card-track-pricing"><%= track.artist %></h2>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" id="footer">
  <div class="footer-links">
    <a href="https://www.facebook.com/DJTsunami/" target="_blank">
      <i class="fab fa-facebook-square"></i>
    </a>
    <a href="https://soundcloud.com/djtsunamichii?fbclid=IwAR1E7fFCVCcJpn2Q-n-L9wPFYu6Bh8dC5ZoO6rnVDBKTjb2HT1B6MXWXk5g" target="_blank">
      <i class="fab fa-soundcloud"></i>
    </a>
    <a href="https://www.instagram.com/djtsunami/" target="_blank">
      <i class="fab fa-instagram"></i>
    </a>
    <a href="https://open.spotify.com/artist/5UqnbnezI2TvaTWKwYhyrP" target="_blank">
      <i class="fab fa-spotify"></i>
    </a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-heart"></i> Music
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shows/index.html.erb
<div class="shows-page">

  <!-- Hero -->
  <%= render 'shared/banner' %>

  <!-- Content -->
  <div class="shows">
    <div class="weekly">
      <div class="day">
        <h3>Monday</h3>
        <p>Spybar</p>
        <p>Chicago, IL</p>
      </div>
      <div class="day">
        <h3>Tuesdy</h3>
        <p></p>
        <p></p>
      </div>
      <div class="day">
        <h3>Wednesday</h3>
        <p></p>
        <p></p>
      </div>
      <div class="day">
        <h3>Thursday</h3>
        <p>Potters</p>
        <p>Naperville, IL</p>
      </div>
      <div class="day">
        <h3>Friday</h3>
        <p></p>
        <p></p>
      </div>
      <div class="day">
        <h3>Saturday</h3>
        <p></p>
        <p></p>
      </div>
      <div class="day">
        <h3>Sunday</h3>
        <p>Your Mom's</p>
        <p>House</p>
      </div>
    </div>
    <div class="container upcoming">
      <h2>Upcoming Shows</h2>
      <% @shows.each do |show| %>
        <div class="show">
          <p><%= show.date %></p>
          <p><%= show.name %></p>
          <p><%= show.location %></p>
        </div>
      <% end %>
    </div>
  </div>
  <!-- Footer -->
  <%= render 'shared/footer' %>
</div>

app/views/shows/new.html.erb
<h1>Shows#new</h1>
<p>Find me in app/views/shows/new.html.erb</p>

app/views/shows/show.html.erb
<h1>Shows#show</h1>
<p>Find me in app/views/shows/show.html.erb</p>

app/views/shows/update.html.erb
<h1>Shows#update</h1>
<p>Find me in app/views/shows/update.html.erb</p>

app/views/tracks/index.html.erb
<div class="music">
  <!-- Hero -->
  <%= render 'shared/banner' %>
  <!-- Content -->
  <div class="releases">
    <h2>Orginal Releases</h2>
    <div class="cards">
      <%= render 'shared/card-track' %>
    </div>
  </div>
  <div class="container media-players">
    <h1>Listen Here</h1>
    <div class="players">
      <div class="player soundcloud">
        <iframe width="300" height="400" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users/1626228&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
      </div>
      <div class="player spotify">
        <iframe src="https://open.spotify.com/embed/artist/5UqnbnezI2TvaTWKwYhyrP" width="300" height="400" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
      </div>
    </div>
  </div>
  <%= render 'shared/footer'  %>
</div>